[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app-core"
version = "1.0.0"
requires-python = ">=3.12"
description = ""
authors = [ { name = "Your Name" }, { email = "email@example.com" } ]
keywords = []
dependencies = []

[project.optional-dependencies]
