[tool.poetry]
name = "fastapi-di"
version = "1.0.0"
description = ""
authors = ["Your Name <email@gmail.com>"]
license = "MIT"
keywords = []

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
